/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lpcdm' at '17-7-21 上午9:40' with Gradle 3.2
 *
 * @author lpcdm, @date 17-7-21 上午9:40
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
